// <auto-generated />
using System;
using Agency.Services.ReservationAPI.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agency.Services.ReservationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250529184813_AddReservationToDb")]
    partial class AddReservationToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agency.Services.ReservationAPI.Domain.Entities.ReservationDetails", b =>
                {
                    b.Property<Guid>("ReservationDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservationHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationDetailsId");

                    b.HasIndex("ReservationHeaderId");

                    b.ToTable("ReservationDetails");
                });

            modelBuilder.Entity("Agency.Services.ReservationAPI.Domain.Entities.ReservationHeader", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId");

                    b.ToTable("ReservationHeaders");
                });

            modelBuilder.Entity("Agency.Services.ReservationAPI.Domain.Entities.ReservationDetails", b =>
                {
                    b.HasOne("Agency.Services.ReservationAPI.Domain.Entities.ReservationHeader", "ReservationHeader")
                        .WithMany()
                        .HasForeignKey("ReservationHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationHeader");
                });
#pragma warning restore 612, 618
        }
    }
}
